include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.mocks.dart"

linter:
  rules:
    prefer_relative_imports: true
    sort_pub_dependencies: false
    use_build_context_synchronously: false
    always_use_package_imports: false
    depend_on_referenced_packages: false
    require_trailing_commas: false
    avoid_dynamic_calls: false
    avoid_void_async: false
