// Mocks generated by Mockito 5.1.0 from annotations
// in app_tdd/test/presentation/cubits/home_page_cubit_test.dart.
// Do not manually edit this file.

import 'package:app_tdd/business/entities/convertion.dart' as _i3;
import 'package:app_tdd/business/usecases/convert_currency.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ConvertCurrency].
///
/// See the documentation for Mockito's code generation for more information.
class MockConvertCurrency extends _i1.Mock implements _i2.ConvertCurrency {
  MockConvertCurrency() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double call(_i3.Convertion? convertion) =>
      (super.noSuchMethod(Invocation.method(#call, [convertion]),
          returnValue: 0.0) as double);
}
